//Include file for NS about screens
const
  scCompany = 'Netlegger Systems';
  scCopyright = 'Copyright 2002,2003';
  scURL = 'http://www.netlegger.net';
  scSupport = 'support@netlegger.net';
  scSupportMail = 'mailto:support@netlegger.net';

  //Program related info
  scMyProgram = 'Netlegger.LargeEdit.1'; // Used for Registry File Associations
  scMyProgramDescr = 'Text File'; // Description of
  scMyIcon = 'LargeEdit.ico';
  scFriendlyName = 'Large Edit';
  scProductImg = 'LE.bmp';

  //Spelling Dictionary Download Site
  scDownloadDic = 'http://www.netlegger.net/largeedit/dictionary.html';
